import numpy as np
import sympy as sp

from prg.models.nonlinear.base_model_fxhx import BaseModelFxHx
from prg.utils.exceptions import NumericalError

__all__ = ["Model_x1_y1_markov_naive"]


class Model_x1_y1_markov_naive(BaseModelFxHx):
    """
    Misspecified Markov model for use as a naive EKF baseline.

    This model ignores the pairwise back-action structure (y -> x coupling).
    It is intentionally wrong for data generated by Model_x1_y1_pairwise_param
    with b > 0, and serves as a baseline showing what a practitioner unaware
    of the pairwise structure would implement.

    State transition (Markov, no y coupling):
        f(x, v^x) = a*x + v^x           <- misses b*tanh(y_{n-1}) term

    Observation (instantaneous, no y memory):
        h(x, v^y) = d*sin(x/20) + v^y   <- misses c*y_{n-1} term

    Parameters
    ----------
    a : float
        Auto-regressive coefficient.
    d : float
        Amplitude of the sinusoidal observation.
    q_x : float
        Variance of the state noise (should match true model).
    q_y : float
        Variance of the observation noise (should match true model).
    """

    def __init__(
        self,
        a: float = 0.50,
        d: float = 2.0,
        q_x: float = 0.04,
        q_y: float = 0.025,
    ):
        self.a = float(a)
        self.d = float(d)

        super().__init__(dim_x=1, dim_y=1, model_type="nonlinear")

        try:
            self.mQ  = np.array([[q_x, 0.0], [0.0, q_y]])
            self.mz0 = np.zeros((self.dim_xy, 1))
            self.Pz0 = np.eye(self.dim_xy) * 0.1

        except (ValueError, np.exceptions.AxisError) as e:
            raise NumericalError(
                f"[{self.MODEL_NAME}] Initialization failed: {e}"
            ) from e

    def symbolic_model(self, sx, st, su):
        x, t, u = sx[0], st[0], su[0]

        sfx = sp.Matrix([self.a * x + t])
        shx = sp.Matrix([self.d * sp.sin(x / 20) + u])

        return sfx, shx
